/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: cms/schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: lib/sanity/queries.ts
// Variable: BLOG_LIST_QUERY
// Query: *[  _type == "post"   && defined(slug.current)  ] | order(publishedAt desc) {    _id,    title,    publishedAt,    slug,    category -> {name},    image,  }
export type BLOG_LIST_QUERY_RESULT = Array<never>;

// Source: lib/sanity/queries.ts
// Variable: BLOG_POST_QUERY
// Query: *[  _type == "post"   && defined(slug.current)   && slug.current == $slug  ] | order(publishedAt desc) [0] {    _id,    title,    slug,    publishedAt,    category -> {name, slug},    description,    image,    body  }
export type BLOG_POST_QUERY_RESULT = null;

// Source: lib/sanity/queries.ts
// Variable: CATEGORY_LIST_QUERY
// Query: *[  _type == "category"   && defined(slug.current)  ] | order(name asc) {    _id,    name,    slug  }
export type CATEGORY_LIST_QUERY_RESULT = Array<never>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[\n  _type == "post" \n  && defined(slug.current)\n  ] | order(publishedAt desc) {\n    _id,\n    title,\n    publishedAt,\n    slug,\n    category -> {name},\n    image,\n  }': BLOG_LIST_QUERY_RESULT;
    '*[\n  _type == "post" \n  && defined(slug.current) \n  && slug.current == $slug\n  ] | order(publishedAt desc) [0] {\n    _id,\n    title,\n    slug,\n    publishedAt,\n    category -> {name, slug},\n    description,\n    image,\n    body\n  }': BLOG_POST_QUERY_RESULT;
    '*[\n  _type == "category" \n  && defined(slug.current)\n  ] | order(name asc) {\n    _id,\n    name,\n    slug\n  }': CATEGORY_LIST_QUERY_RESULT;
  }
}
